[package]
name = "elites-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "elites"
crate-type = ["cdylib"]

[dependencies]
elites = { path = ".." }  # Reference main library
pyo3 = { version = "0.19", features = ["extension-module"] }
numpy = "0.19"
rand = "0.8" 